### ISSUE TITLE
Flytt tbx-ap-no til eget repo

### ISSUE THREAD

**Issue by stigbd** [difi/data-docs#19]
Bør være likt som skos-ap-no repo.

**Comment by oystein-asnes** [comment]
Dette gjeld altså https://github.com/difi/data-docs/tree/master/begrep-tbx-ap-no. Output her er https://doc.difi.no/data/begrep-tbx-ap-no/  

[Team rammeverk admin](https://github.com/orgs/difi/teams/rammeverk-admin) skal ha admin-tilgang.

**Comment by jimjyang** [comment]
Fiksa av @stigbd 8/6-20, til informasjonsforvaltning.
