### ISSUE TITLE
Flytt forvaltningsstandard-begrepsbeskrivelser til eget repo

### ISSUE THREAD

**Issue by stigbd** [difi/data-docs#20]

**Comment by oystein-asnes** [comment]
Repoet er opprettet og standard og tilhørende veileder er flytta hit:  https://github.com/difi/forvaltningsstandard-begrep. Det er noen mindre følgefeil ma pga djuplenker i veilederen. Se detaljer her: https://travis-ci.org/difi/forvaltningsstandard-begrep/

**Comment by jimjyang** [comment]
Utført
